### ISSUE TITLE
About the order of training segmentation model and the reconstruct model @Endless-Hao

### ISSUE THREAD

**Issue by pengyaru** [Endless-Hao/DDFSeg#1]
hello @Endless-Hao, I want to know if the segmentation model needs pre-training with the source domain dataset before training the segmentation and reconstruct models together with source and target domain datasets.
Besides, I want to know if there is a pytorch version, if so, can you send me a copy？
Hope your reply

**Comment by Endless-Hao** [comment]
Hello, @pengyaru  Thank you for your attention. The segmentation model does not need pre-training.
